system:
    default:
        field_templates:
            - { template: "@NetgenContentTypeList/ngclasslist_content_field.html.twig", priority: 0 }
        fielddefinition_settings_templates:
            - { template: "@NetgenContentTypeList/field_definition/view/ngclasslist.html.twig", priority: 0 }
