services:
    netgen_class_list.field_type:
        class: Netgen\Bundle\ContentTypeListBundle\Core\FieldType\ContentTypeList\Type
        parent: Ibexa\Core\FieldType\FieldType
        tags:
            - { name: ibexa.field_type, alias: ngclasslist }

    netgen_class_list.field_type.indexable:
        class: Ibexa\Core\FieldType\Unindexed
        tags:
            - { name: ibexa.field_type.indexable, alias: ngclasslist }

    netgen_class_list.field_type.legacy.converter:
        class: Netgen\Bundle\ContentTypeListBundle\Core\Persistence\Legacy\Content\FieldValue\Converter\ContentTypeListConverter
        tags:
            - { name: ibexa.field_type.storage.legacy.converter, alias: ngclasslist }

    netgen_class_list.field_type.form_mapper:
        class: Netgen\Bundle\ContentTypeListBundle\Core\FieldType\ContentTypeList\FormMapper
        tags:
            - { name: ibexa.admin_ui.field_type.form.mapper.value, fieldType: ngclasslist }

    netgen_class_list.field_type.form:
        class: Netgen\Bundle\ContentTypeListBundle\Form\Type\FieldType\ContentTypeListFieldType
        arguments:
            - "@ibexa.api.service.content_type"
            - "@ibexa.api.service.field_type"
        tags:
            - { name: form.type }
